import React, { Component, useEffect, useState } from "react";
import { Link, useLocation } from "react-router-dom";

import Slider from "react-slick";
import vid from "../media/video.mp4";

import present from "../media/present.png";
import mainlogo from "../media/headerlogo.png";
import Footer from "../components/Footer";
import { Swiper, SwiperSlide } from "swiper/react";
import SwiperCore, {
  EffectFade,
  Navigation,
  Pagination,
  Scrollbar,
  A11y,
} from "swiper";

import "swiper/swiper.scss";
import "swiper/components/effect-fade/effect-fade.scss";
import "swiper/swiper.scss";
import "swiper/components/navigation/navigation.scss";
import "swiper/components/pagination/pagination.scss";
import "swiper/components/scrollbar/scrollbar.scss";
SwiperCore.use([EffectFade, Navigation, Pagination, Scrollbar, A11y]);

const Home = (params) => {
  const [togglePresent, setTogglePresnt] = useState(true);
  const [counter, setCounter] = useState(0);
  const sliderCounter = params.sliderCounter;
  useEffect(() => {
    const rightBtn = document.getElementsByClassName("swiper-button-prev");
    setTimeout(() => {
      setTogglePresnt(false);
    }, 3500);
  }, []);
  useEffect(() => {
    sliderCounter(counter);
  }, [counter]);
  const location = useLocation();
  return (
    <div className="position-relative">
      <div className={togglePresent ? "loader" : "loader active"}>
        <img src={present} alt="" />
      </div>
      {location.pathname === "/" ? (
        <div className="home">
          <div className="logo-home-mob">
            <img src={mainlogo} alt="" />
          </div>
          <div className="d-none d-md-block">
            <Swiper
              effect="fade"
              direction="vertical"
              spaceBetween={0}
              slidesPerView={1}
              navigation
              // pagination={{ clickable: false }}
              scrollbar={{ draggable: true }}
              onSlideChange={(swiper) => setCounter(swiper.realIndex)}
            >
              <SwiperSlide>
                <div className="vid">
                  <video width="800" heigh="800" autoPlay muted>
                    <source
                      src={vid}
                      type="video/mp4"
                    />
                  </video>
                </div>
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400604/sd1_ovepqq.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403312/Sehsucht_Atelier_Henerico_Rossi_01_bgk0d1.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406650/Sehsucht_Atelier_Henerico_Rossi_01_hmiya2.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400604/sd2_ghbp4z.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403355/Sehsucht_Atelier_Henerico_Rossi_02_rriluc.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406649/Sehsucht_Atelier_Henerico_Rossi_02_brtahu.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400604/sd3_nywxlc.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403357/Sehsucht_Atelier_Henerico_Rossi_04_rpwys1.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406650/Sehsucht_Atelier_Henerico_Rossi_03_fridch.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400604/sd4_o5krei.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403356/Sehsucht_Atelier_Henerico_Rossi_05_m7kwqh.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406651/Sehsucht_Atelier_Henerico_Rossi_04_lmioyb.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400592/sd5_ia9hmo.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403358/Sehsucht_Atelier_Henerico_Rossi_06_rm8xtc.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406650/Sehsucht_Atelier_Henerico_Rossi_05_nnico4.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400593/sd6_cudav9.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403361/Sehsucht_Atelier_Henerico_Rossi_13_zghbds.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406650/Sehsucht_Atelier_Henerico_Rossi_06_c0hgbh.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400592/sd7_c1mkdz.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403351/Sehsucht_Atelier_Henerico_Rossi_017_goueiw.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406650/Sehsucht_Atelier_Henerico_Rossi_07_vyghwn.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400593/sd8_tmhm8y.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403352/Sehsucht_Atelier_Henerico_Rossi_018_mkqkqm.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406650/Sehsucht_Atelier_Henerico_Rossi_07_vyghwn.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400593/sd9_njmotw.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403354/Sehsucht_Atelier_Henerico_Rossi_019_f2igow.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406651/Sehsucht_Atelier_Henerico_Rossi_08_foeor2.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400592/sd10_ggdtf8.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403309/Sehsucht_Atelier_Henerico_Rossi_0111_sghrzf.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406652/Sehsucht_Atelier_Henerico_Rossi_09_gpcgel.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400594/sd11_bprdlk.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403309/Sehsucht_Atelier_Henerico_Rossi_0111_sghrzf.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406651/Sehsucht_Atelier_Henerico_Rossi_10_dslidn.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400594/sd12_aku9hy.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403316/Sehsucht_Atelier_Henerico_Rossi_0118_vgmxde.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406651/Sehsucht_Atelier_Henerico_Rossi_10_dslidn.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400594/sd14_uflbrm.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403319/Sehsucht_Atelier_Henerico_Rossi_0119_yn3jdn.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406652/Sehsucht_Atelier_Henerico_Rossi_11_zafovm.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400601/sd15_cyufup.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403320/Sehsucht_Atelier_Henerico_Rossi_0120_sfdxaq.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406653/Sehsucht_Atelier_Henerico_Rossi_12_gyjvfp.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400595/sd16_ugcgxt.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403321/Sehsucht_Atelier_Henerico_Rossi_0121_iq175h.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406653/Sehsucht_Atelier_Henerico_Rossi_14_em57ol.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400599/sd17_zaen76.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403320/Sehsucht_Atelier_Henerico_Rossi_0122_btuhmc.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406654/Sehsucht_Atelier_Henerico_Rossi_15_rbpts9.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400597/sd19_njxtnq.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403320/Sehsucht_Atelier_Henerico_Rossi_0123_npyk91.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406654/Sehsucht_Atelier_Henerico_Rossi_16_c1uxuj.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400599/sd20_nmcfb3.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403323/Sehsucht_Atelier_Henerico_Rossi_0124_ygktsn.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406653/Sehsucht_Atelier_Henerico_Rossi_17_zfbewv.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400599/sd22_w5qgae.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403324/Sehsucht_Atelier_Henerico_Rossi_0125_kqw4hx.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406654/Sehsucht_Atelier_Henerico_Rossi_18_hl2gli.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400601/sd23_u3ilsj.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403324/Sehsucht_Atelier_Henerico_Rossi_0125_kqw4hx.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406655/Sehsucht_Atelier_Henerico_Rossi_19_hacwa1.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400600/sd24_vhcbt0.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403329/Sehsucht_Atelier_Henerico_Rossi_0126_w0kta8.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406656/Sehsucht_Atelier_Henerico_Rossi_20_x1gpzk.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400604/sd25_nh0ofr.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403328/Sehsucht_Atelier_Henerico_Rossi_0128_l2gbgz.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406655/Sehsucht_Atelier_Henerico_Rossi_21_xoyjvj.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400601/sd26_xylm6k.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403327/Sehsucht_Atelier_Henerico_Rossi_0129_pvaojg.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406656/Sehsucht_Atelier_Henerico_Rossi_22_cvojuf.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400603/sd27_efgzwp.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403329/Sehsucht_Atelier_Henerico_Rossi_0130_hfhzrp.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406656/Sehsucht_Atelier_Henerico_Rossi_23_d7yqq2.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400602/sd28_qbb2ya.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403332/Sehsucht_Atelier_Henerico_Rossi_0131_ewylz8.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406656/Sehsucht_Atelier_Henerico_Rossi_24_zrgulb.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403336/Sehsucht_Atelier_Henerico_Rossi_0132_jgawky.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406656/Sehsucht_Atelier_Henerico_Rossi_25_randzh.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403333/Sehsucht_Atelier_Henerico_Rossi_0133_vnzolo.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406656/Sehsucht_Atelier_Henerico_Rossi_26_bmmkfa.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403333/Sehsucht_Atelier_Henerico_Rossi_0134_p6yylh.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406660/Sehsucht_Atelier_Henerico_Rossi_27_d38exp.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403333/Sehsucht_Atelier_Henerico_Rossi_0134_p6yylh.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406658/Sehsucht_Atelier_Henerico_Rossi_28_zrfqgy.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403337/Sehsucht_Atelier_Henerico_Rossi_0135_myirsu.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406657/Sehsucht_Atelier_Henerico_Rossi_29_rzcz5g.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403339/Sehsucht_Atelier_Henerico_Rossi_0136_xd5dig.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406658/Sehsucht_Atelier_Henerico_Rossi_30_rlnfxa.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403339/Sehsucht_Atelier_Henerico_Rossi_0136_xd5dig.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406662/Sehsucht_Atelier_Henerico_Rossi_31_cviz45.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403339/Sehsucht_Atelier_Henerico_Rossi_0136_xd5dig.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406661/Sehsucht_Atelier_Henerico_Rossi_32_mi1b2b.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403342/Sehsucht_Atelier_Henerico_Rossi_0137_qpuyws.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406660/Sehsucht_Atelier_Henerico_Rossi_33_pusbvm.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403343/Sehsucht_Atelier_Henerico_Rossi_0138_fojwha.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406662/Sehsucht_Atelier_Henerico_Rossi_34_j9z0uk.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403343/Sehsucht_Atelier_Henerico_Rossi_0139_ryu0xo.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406662/Sehsucht_Atelier_Henerico_Rossi_35_nt950n.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403341/Sehsucht_Atelier_Henerico_Rossi_0141_jreuib.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406663/Sehsucht_Atelier_Henerico_Rossi_36_dfsxn0.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403345/Sehsucht_Atelier_Henerico_Rossi_0142_evtx2y.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406662/Sehsucht_Atelier_Henerico_Rossi_37_tm84s6.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403348/Sehsucht_Atelier_Henerico_Rossi_0143_jki9wu.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406665/Sehsucht_Atelier_Henerico_Rossi_38_jz2gpv.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403355/Sehsucht_Atelier_Henerico_Rossi_0144_k82u3t.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406665/Sehsucht_Atelier_Henerico_Rossi_39_ddkwqs.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403352/Sehsucht_Atelier_Henerico_Rossi_0146_bypdvd.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406666/Sehsucht_Atelier_Henerico_Rossi_40_vnouum.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403352/Sehsucht_Atelier_Henerico_Rossi_0145_wfueqg.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406666/Sehsucht_Atelier_Henerico_Rossi_41_misymd.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403348/Sehsucht_Atelier_Henerico_Rossi_0147_qius9b.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406665/Sehsucht_Atelier_Henerico_Rossi_42_zli2os.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406666/Sehsucht_Atelier_Henerico_Rossi_43_j227ii.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406668/Sehsucht_Atelier_Henerico_Rossi_44_vpxq8u.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406667/Sehsucht_Atelier_Henerico_Rossi_45_ekrnej.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406668/Sehsucht_Atelier_Henerico_Rossi_46_qemtn5.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406669/Sehsucht_Atelier_Henerico_Rossi_47_befkct.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406668/Sehsucht_Atelier_Henerico_Rossi_48_nhejvi.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406668/Sehsucht_Atelier_Henerico_Rossi_49_ctrp7a.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406669/Sehsucht_Atelier_Henerico_Rossi_50_huvkv5.jpg"
                  alt=""
                />
              </SwiperSlide>
            </Swiper>
          </div>
          <div className="d-block d-md-none">
            <Swiper
              effect="fade"
              // direction="virtual"
              spaceBetween={0}
              slidesPerView={1}
              navigation
              
              // pagination={{ clickable: false }}
              // scrollbar={{ draggable: true }}
              onSlideChange={(swiper) => setCounter(swiper.realIndex)}
            >
              <SwiperSlide>
                <div className="vid">
                  <video width="800" heigh="800" autoPlay muted>
                    <source
                      src="https://res.cloudinary.com/dplknnqsx/video/upload/v1616401779/video_len9kz.mp4"
                      type="video/mp4"
                    />
                  </video>
                </div>
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400604/sd1_ovepqq.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403312/Sehsucht_Atelier_Henerico_Rossi_01_bgk0d1.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406650/Sehsucht_Atelier_Henerico_Rossi_01_hmiya2.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400604/sd2_ghbp4z.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403355/Sehsucht_Atelier_Henerico_Rossi_02_rriluc.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406649/Sehsucht_Atelier_Henerico_Rossi_02_brtahu.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400604/sd3_nywxlc.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403357/Sehsucht_Atelier_Henerico_Rossi_04_rpwys1.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406650/Sehsucht_Atelier_Henerico_Rossi_03_fridch.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400604/sd4_o5krei.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403356/Sehsucht_Atelier_Henerico_Rossi_05_m7kwqh.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406651/Sehsucht_Atelier_Henerico_Rossi_04_lmioyb.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400592/sd5_ia9hmo.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403358/Sehsucht_Atelier_Henerico_Rossi_06_rm8xtc.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406650/Sehsucht_Atelier_Henerico_Rossi_05_nnico4.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400593/sd6_cudav9.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403361/Sehsucht_Atelier_Henerico_Rossi_13_zghbds.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406650/Sehsucht_Atelier_Henerico_Rossi_06_c0hgbh.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400592/sd7_c1mkdz.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403351/Sehsucht_Atelier_Henerico_Rossi_017_goueiw.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406650/Sehsucht_Atelier_Henerico_Rossi_07_vyghwn.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400593/sd8_tmhm8y.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403352/Sehsucht_Atelier_Henerico_Rossi_018_mkqkqm.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406650/Sehsucht_Atelier_Henerico_Rossi_07_vyghwn.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400593/sd9_njmotw.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403354/Sehsucht_Atelier_Henerico_Rossi_019_f2igow.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406651/Sehsucht_Atelier_Henerico_Rossi_08_foeor2.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400592/sd10_ggdtf8.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403309/Sehsucht_Atelier_Henerico_Rossi_0111_sghrzf.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406652/Sehsucht_Atelier_Henerico_Rossi_09_gpcgel.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400594/sd11_bprdlk.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403309/Sehsucht_Atelier_Henerico_Rossi_0111_sghrzf.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406651/Sehsucht_Atelier_Henerico_Rossi_10_dslidn.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400594/sd12_aku9hy.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403316/Sehsucht_Atelier_Henerico_Rossi_0118_vgmxde.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406651/Sehsucht_Atelier_Henerico_Rossi_10_dslidn.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400594/sd14_uflbrm.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403319/Sehsucht_Atelier_Henerico_Rossi_0119_yn3jdn.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406652/Sehsucht_Atelier_Henerico_Rossi_11_zafovm.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400601/sd15_cyufup.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403320/Sehsucht_Atelier_Henerico_Rossi_0120_sfdxaq.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406653/Sehsucht_Atelier_Henerico_Rossi_12_gyjvfp.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400595/sd16_ugcgxt.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403321/Sehsucht_Atelier_Henerico_Rossi_0121_iq175h.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406653/Sehsucht_Atelier_Henerico_Rossi_14_em57ol.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400599/sd17_zaen76.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403320/Sehsucht_Atelier_Henerico_Rossi_0122_btuhmc.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406654/Sehsucht_Atelier_Henerico_Rossi_15_rbpts9.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400597/sd19_njxtnq.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403320/Sehsucht_Atelier_Henerico_Rossi_0123_npyk91.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406654/Sehsucht_Atelier_Henerico_Rossi_16_c1uxuj.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400599/sd20_nmcfb3.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403323/Sehsucht_Atelier_Henerico_Rossi_0124_ygktsn.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406653/Sehsucht_Atelier_Henerico_Rossi_17_zfbewv.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400599/sd22_w5qgae.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403324/Sehsucht_Atelier_Henerico_Rossi_0125_kqw4hx.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406654/Sehsucht_Atelier_Henerico_Rossi_18_hl2gli.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400601/sd23_u3ilsj.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403324/Sehsucht_Atelier_Henerico_Rossi_0125_kqw4hx.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406655/Sehsucht_Atelier_Henerico_Rossi_19_hacwa1.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400600/sd24_vhcbt0.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403329/Sehsucht_Atelier_Henerico_Rossi_0126_w0kta8.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406656/Sehsucht_Atelier_Henerico_Rossi_20_x1gpzk.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400604/sd25_nh0ofr.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403328/Sehsucht_Atelier_Henerico_Rossi_0128_l2gbgz.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406655/Sehsucht_Atelier_Henerico_Rossi_21_xoyjvj.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400601/sd26_xylm6k.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403327/Sehsucht_Atelier_Henerico_Rossi_0129_pvaojg.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406656/Sehsucht_Atelier_Henerico_Rossi_22_cvojuf.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400603/sd27_efgzwp.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403329/Sehsucht_Atelier_Henerico_Rossi_0130_hfhzrp.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406656/Sehsucht_Atelier_Henerico_Rossi_23_d7yqq2.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-desk"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616400602/sd28_qbb2ya.jpg"
                  alt=""
                />
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403332/Sehsucht_Atelier_Henerico_Rossi_0131_ewylz8.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406656/Sehsucht_Atelier_Henerico_Rossi_24_zrgulb.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403336/Sehsucht_Atelier_Henerico_Rossi_0132_jgawky.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406656/Sehsucht_Atelier_Henerico_Rossi_25_randzh.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403333/Sehsucht_Atelier_Henerico_Rossi_0133_vnzolo.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406656/Sehsucht_Atelier_Henerico_Rossi_26_bmmkfa.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403333/Sehsucht_Atelier_Henerico_Rossi_0134_p6yylh.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406660/Sehsucht_Atelier_Henerico_Rossi_27_d38exp.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403333/Sehsucht_Atelier_Henerico_Rossi_0134_p6yylh.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406658/Sehsucht_Atelier_Henerico_Rossi_28_zrfqgy.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403337/Sehsucht_Atelier_Henerico_Rossi_0135_myirsu.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406657/Sehsucht_Atelier_Henerico_Rossi_29_rzcz5g.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403339/Sehsucht_Atelier_Henerico_Rossi_0136_xd5dig.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406658/Sehsucht_Atelier_Henerico_Rossi_30_rlnfxa.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403339/Sehsucht_Atelier_Henerico_Rossi_0136_xd5dig.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406662/Sehsucht_Atelier_Henerico_Rossi_31_cviz45.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403339/Sehsucht_Atelier_Henerico_Rossi_0136_xd5dig.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406661/Sehsucht_Atelier_Henerico_Rossi_32_mi1b2b.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403342/Sehsucht_Atelier_Henerico_Rossi_0137_qpuyws.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406660/Sehsucht_Atelier_Henerico_Rossi_33_pusbvm.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403343/Sehsucht_Atelier_Henerico_Rossi_0138_fojwha.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406662/Sehsucht_Atelier_Henerico_Rossi_34_j9z0uk.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403343/Sehsucht_Atelier_Henerico_Rossi_0139_ryu0xo.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406662/Sehsucht_Atelier_Henerico_Rossi_35_nt950n.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403341/Sehsucht_Atelier_Henerico_Rossi_0141_jreuib.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406663/Sehsucht_Atelier_Henerico_Rossi_36_dfsxn0.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403345/Sehsucht_Atelier_Henerico_Rossi_0142_evtx2y.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406662/Sehsucht_Atelier_Henerico_Rossi_37_tm84s6.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403348/Sehsucht_Atelier_Henerico_Rossi_0143_jki9wu.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406665/Sehsucht_Atelier_Henerico_Rossi_38_jz2gpv.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403355/Sehsucht_Atelier_Henerico_Rossi_0144_k82u3t.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406665/Sehsucht_Atelier_Henerico_Rossi_39_ddkwqs.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403352/Sehsucht_Atelier_Henerico_Rossi_0146_bypdvd.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406666/Sehsucht_Atelier_Henerico_Rossi_40_vnouum.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403352/Sehsucht_Atelier_Henerico_Rossi_0145_wfueqg.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406666/Sehsucht_Atelier_Henerico_Rossi_41_misymd.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-tab"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616403348/Sehsucht_Atelier_Henerico_Rossi_0147_qius9b.jpg"
                  alt=""
                />
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406665/Sehsucht_Atelier_Henerico_Rossi_42_zli2os.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406666/Sehsucht_Atelier_Henerico_Rossi_43_j227ii.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406668/Sehsucht_Atelier_Henerico_Rossi_44_vpxq8u.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406667/Sehsucht_Atelier_Henerico_Rossi_45_ekrnej.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406668/Sehsucht_Atelier_Henerico_Rossi_46_qemtn5.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406669/Sehsucht_Atelier_Henerico_Rossi_47_befkct.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406668/Sehsucht_Atelier_Henerico_Rossi_48_nhejvi.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406668/Sehsucht_Atelier_Henerico_Rossi_49_ctrp7a.jpg"
                  alt=""
                />
              </SwiperSlide>
              <SwiperSlide>
                <img
                  className="img-mob"
                  src="https://res.cloudinary.com/dplknnqsx/image/upload/v1616406669/Sehsucht_Atelier_Henerico_Rossi_50_huvkv5.jpg"
                  alt=""
                />
              </SwiperSlide>
            </Swiper>
          </div>
        </div>
      ) : null}
    </div>
  );
};

export default Home;
